spring:
  application:
    name: trade-aggregation-service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: trade-aggregation
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  data:
    mongodb:
      host: localhost
      port: 27017
      database: trade_aggregation

server:
  port: 8083

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

logging:
  level:
    root: INFO
    com.example.tradeaggregation: DEBUG

trade-aggregation:
  window:
    size: 60  # Aggregation window size in seconds
  batch:
    size: 100  # Maximum batch size for aggregation
  persistence:
    enabled: true
    cleanup-older-than-days: 30